# Generated by Django 4.1.2 on 2022-11-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_product_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='details',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
