# Generated by Django 4.1.2 on 2022-11-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.FileField(upload_to=''),
        ),
    ]
